[settings]
launch_on_startup = false
always_on_top = false
minimize_to_tray = true
confirm_on_exit = true
restart_on_crash = false
prevent_sleep = false
start_minimized = false
remux_raw_aac_to_m4_a = true
recordings_folder = "My recordings"
file_name_template = "%t_%r-%M-%d_%h-%m-%s"
language = "Polish"
