<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <ItemGroup>
    <ProjectReference Include="..\StreamRecorder.Core\StreamRecorder.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\locales\*.json" Link="locales\%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <AssemblyName>StreamRecorder</AssemblyName>
    <Product>StreamRecorder</Product>
    <Version>0.2.0-alpha7</Version>
  </PropertyGroup>

</Project>
